# Generated by Django 3.1.4 on 2021-11-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juplu', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Description', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='img'),
        ),
    ]
